# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-28 19:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='editor.Character')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='attributeadvantage',
            name='max',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='advantage',
            name='conditions',
            field=models.ManyToManyField(blank=True, related_name='_advantage_conditions_+', to='editor.Advantage'),
        ),
    ]
