# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-21 20:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_index=True, max_length=100)),
                ('last_name', models.CharField(db_index=True, max_length=100)),
                ('nickname', models.CharField(db_index=True, max_length=100)),
                ('pc', models.IntegerField(default=50)),
                ('px', models.IntegerField(default=0)),
                ('advantages', models.ManyToManyField(blank=True, related_name='advantages_characters', to='editor.Advantage')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='characters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='attributeadvantage',
            name='cost_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attributeadvantage',
            name='label_limit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advantage', to='editor.Label'),
        ),
        migrations.AlterField(
            model_name='attributeadvantage',
            name='advantage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attribute', to='editor.Advantage'),
        ),
        migrations.AlterField(
            model_name='attributeadvantage',
            name='attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advantage', to='editor.Attribute'),
        ),
    ]
