# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-02 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_auto_20180528_1914'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribute',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='attributelevel',
            options={'ordering': ['level']},
        ),
        migrations.AddField(
            model_name='character',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/characters/'),
        ),
        migrations.AddField(
            model_name='page',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/pages/'),
        ),
        migrations.AddField(
            model_name='page',
            name='drawing',
            field=models.FileField(blank=True, null=True, upload_to='drawing/pages/'),
        ),
        migrations.AddField(
            model_name='page',
            name='quote',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='section',
            name='drawing',
            field=models.FileField(blank=True, null=True, upload_to='drawing/sections/'),
        ),
        migrations.AddField(
            model_name='section',
            name='quote',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='total_pc',
            field=models.IntegerField(default=300),
        ),
    ]
