# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-22 13:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0003_auto_20180602_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeCharacter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus', models.IntegerField(default=1)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.Attribute')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='attribute_bonuses',
            field=models.ManyToManyField(blank=True, related_name='attribute_bonuses_characters', to='editor.Attribute'),
        ),
        migrations.AlterField(
            model_name='character',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='media/audio/characters/'),
        ),
        migrations.AlterField(
            model_name='page',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='media/audio/pages/'),
        ),
        migrations.AlterField(
            model_name='page',
            name='drawing',
            field=models.FileField(blank=True, null=True, upload_to='media/drawing/pages/'),
        ),
        migrations.AlterField(
            model_name='section',
            name='drawing',
            field=models.FileField(blank=True, null=True, upload_to='media/drawing/sections/'),
        ),
        migrations.AddField(
            model_name='attributecharacter',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.Character'),
        ),
    ]
