# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-29 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0004_auto_20180622_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='drawing',
            field=models.ImageField(blank=True, null=True, upload_to='media/drawing/characters/'),
        ),
        migrations.AlterField(
            model_name='page',
            name='drawing',
            field=models.ImageField(blank=True, null=True, upload_to='media/drawing/pages/'),
        ),
    ]
