# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-20 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0006_auto_20180629_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
