# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-29 13:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0007_section_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='labels',
        ),
        migrations.AddField(
            model_name='attribute',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='label_attributes', to='editor.Label'),
        ),
    ]
